name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Please (plz)
      run: |
        curl -s https://get.please.build | bash
        export PATH=$PATH:/usr/local/bin

    - name: Build
      run: plz build //src/...

    - name: Test
      run: plz test //src/...
